#!/bin/sh

# Install flatpak
sudo dnf install -y flatpak

# Add flathub repository
sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

# Add gnome software
sudo dnf install -y gnome-software
