#!/bin/sh

sudo dnf check-update 
sudo dnf install -y scrot bat zip pulsemixer pulseaudio-utils gcc-c++ unzip curl wget git ca-certificates ripgrep xclip jq tldr shutter python3-pip shellcheck mpv ffmpeg brotli p7zip p7zip-plugins meson ninja-build

mkdir -p ~/.local/bin
ln -s /usr/bin/bat ~/.local/bin/bat

