#!/bin/sh

# Setup repo for preload
sudo dnf copr enable -y elxreno/preload

# Install preload
sudo dnf install -y preload

# Disable plymouth
sudo sed -i 's#^GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"$#GRUB_CMDLINE_LINUX_DEFAULT="fsck.mode=skip quiet splash"#g' /etc/default/grub

# Uninstall snaps
# sudo dnf remove -y snapd && rm -rf ~/snap && sudo rm -rf /snap /var/snap /var/lib/snapd

# Don't let the network stall the boot process
sudo systemctl disable NetworkManager-wait-online.service
