#!/bin/sh

# Install flatpak
sudo pacman -S --noconfirm flatpak

# Add flathub repository
sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

# Add gnome software
sudo pacman -S --noconfirm gnome-software

