#!/bin/sh

# Install dependencies
sudo pacman -S --noconfirm --needed wget tar grub

# Change this to your favourite distro or manufacturer
THEME="system76"

# Create Downloads directory if it doesn't exist
mkdir -p "$HOME/Downloads"

# Download grub theme
wget "https://github.com/AdisonCavani/distro-grub-themes/releases/download/v3.2/$THEME.tar" -O "$HOME/Downloads/$THEME.tar"

# Go to the download folder
cd "$HOME/Downloads" || exit

# Make a directory that holds the files
mkdir -p "$THEME"

# Untar it
tar -xvf "$THEME.tar" -C "./$THEME"

# Create the grub themes dir
sudo mkdir -p /boot/grub/themes

# Move the newly created theme there
sudo mv "$HOME/Downloads/$THEME" "/boot/grub/themes/"

# In case of dual or tripple booting
sudo sed -i 's/^#GRUB_DISABLE_OS_PROBER=false/GRUB_DISABLE_OS_PROBER=false/' /etc/default/grub

# Add grub theme
THEME_LINE="GRUB_THEME=\"/boot/grub/themes/$THEME/theme.txt\""
if ! tail -n 1 /etc/default/grub | grep -Fxq "$THEME_LINE"; then
  echo "$THEME_LINE" | sudo tee -a /etc/default/grub
fi

# Update grub
sudo grub-mkconfig -o /boot/grub/grub.cfg

