#!/bin/sh

# Disable plymouth
sudo sed -i 's#^GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"$#GRUB_CMDLINE_LINUX_DEFAULT="fsck.mode=skip quiet splash"#g' /etc/default/grub

# Don't let the network stall the boot process
sudo systemctl disable NetworkManager-wait-online.service
