#!/bin/sh

# Install flatpak
sudo pkg install -y flatpak

# Add flathub repository
sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

# Add gnome software
sudo pkg install -y gnome-software

