#!/bin/sh

# Install dependencies
sudo pkg install -y wget tar

# Change this to your favourite distro or manufacturer
THEME="system76"

# Create Downloads directory if it doesn't exist
mkdir -p "$HOME/Downloads"

# Download grub theme (This part can still be done)
wget "https://github.com/AdisonCavani/distro-grub-themes/releases/download/v3.2/$THEME.tar" -O "$HOME/Downloads/$THEME.tar"

# Go to the download folder
cd "$HOME/Downloads" || exit

# Make a directory that holds the files
mkdir -p "$THEME"

# Untar it (This part can still be done)
tar -xvf "$THEME.tar" -C "./$THEME"

# The following sections are specific to GRUB on Linux systems.
# FreeBSD uses a different bootloader by default (BSD Bootloader).
# If you have manually installed and configured GRUB on FreeBSD to boot other OSes,
# you would need to adapt these paths and commands accordingly.

# # Create the grub themes dir
# sudo mkdir -p /boot/grub/themes

# # Move the newly created theme there
# sudo mv "$HOME/Downloads/$THEME" "/boot/grub/themes/"

# # In case of dual or tripple booting (GRUB specific config file)
# sudo sed -i 's/^#GRUB_DISABLE_OS_PROBER=false/GRUB_DISABLE_OS_PROBER=false/' /etc/default/grub

# # Add grub theme (GRUB specific config file)
# THEME_LINE="GRUB_THEME=\"/boot/grub/themes/$THEME/theme.txt\""
# if ! tail -n 1 /etc/default/grub | grep -Fxq "$THEME_LINE"; then
#   echo "$THEME_LINE" | sudo tee -a /etc/default/grub
# fi

# # Update grub (GRUB specific command)
# # e.g., sudo grub-mkconfig -o /boot/grub/grub.cfg (if GRUB is installed)

echo "GRUB theme downloaded and extracted to $HOME/Downloads/$THEME."
echo "GRUB configuration steps are commented out as FreeBSD does not use GRUB by default."
echo "If you use GRUB on FreeBSD, please adapt the commented sections manually."
