#!/bin/sh

# Add OneFetch repository
sudo add-apt-repository -y ppa:o2sh/onefetch

# Update
sudo apt-get update -y

# Install fun tools
sudo apt install -y yt-dlp bashtop onefetch neofetch htop glances cbonsai cmatrix lsd

# Install Asciiquarium
sudo add-apt-repository -y ppa:ytvwld/asciiquarium
sudo apt install -y asciiquarium

# Install somafm cli
git clone https://github.com/rockymadden/somafm-cli.git "$HOME/somafm"
cd "$HOME/somafm"
make
make install
