#!/bin/sh

# Install preload
sudo apt install preload

# Disable plymouth
sudo sed -i 's#^GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"$#GRUB_CMDLINE_LINUX_DEFAULT="fsck.mode=skip quiet splash"#g' /etc/default/grub

# Uninstall snaps
# sudo apt purge -y snapd && rm -rf ~/snap && sudo rm -rf /snap && sudo rm -rf /var/snap && sudo rm -rf /var/lib/snapd && sudo apt-mark hold snap

# Don't let the network stall the boot process
sudo systemctl disable NetworkManager-wait-online.service
